### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte

### ISSUE THREAD

**Issue by reasv** [exo-explore/exo#121]
Getting this error at startup (python3 main.py) on WSL2 on Windows11 (Nvidia/CUDA), after git clone, install.sh, and installing pytorch.

```
  _____  _____
 / _ \ \/ / _ \
|  __/>  < (_) |
 \___/_/\_\___/

Detected system: Linux
Using inference engine: TinygradDynamicShardInferenceEngine
[52676, 55838]
Traceback (most recent call last):
  File "/mnt/q/projects/exo/main.py", line 45, in <module>
    node = StandardNode(
           ^^^^^^^^^^^^^
  File "/mnt/q/projects/exo/exo/orchestration/standard_node.py", line 38, in __init__
    self.device_capabilities = device_capabilities()
                               ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/q/projects/exo/exo/topology/device_capabilities.py", line 122, in device_capabilities
    return linux_device_capabilities()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/q/projects/exo/exo/topology/device_capabilities.py", line 162, in linux_device_capabilities
    gpu_name = pynvml.nvmlDeviceGetName(handle).upper()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/q/projects/exo/.venv/lib/python3.11/site-packages/pynvml/nvml.py", line 1744, in wrapper
    return res.decode()
           ^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte
```

**Comment by reasv** [comment]
It appears the GPU name the API returns is
```
b'\xf8\x95\xa0\x81\x8e\xf8\x91\x80\x81\x89\xf8\x90\x90\x81\x89\xf8\x91\xb0\x80\xa0\xf8\x91\xa0\x81\xa5\xf8\x9c\xa0\x81\xaf\xf8\x99\x90\x81\xa3\xf8\x94\xa0\x80\xa0\xf8\x96\x80\x81\x94\xf8\x8d\x80\x80\xa0\xf8\x8e\x90\x80\xb00'
```

**Comment by reasv** [comment]
It appears to have been an upstream CUDA bug fixed by downloading the latest drivers.
