### ISSUE TITLE
python issues

### ISSUE THREAD

**Issue by zaidzameeer010** [exo-explore/exo#163]
first tried to use it with python 3.11.9, but it crashed with this error:

Cancelling 0 outstanding tasks
Traceback (most recent call last):
  File "D:\conda\exo\main.py", line 178, in <module>
    loop.run_until_complete(main())
  File "C:\Users\zaidz\anaconda3\envs\exo\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\conda\exo\main.py", line 164, in main
    loop.add_signal_handler(s, handle_exit)
  File "C:\Users\zaidz\anaconda3\envs\exo\Lib\asyncio\events.py", line 578, in add_signal_handler
    raise NotImplementedError
NotImplementedError

then i looked at the documentation and i found that they said you need python 3.12.0 specificly but after that it gave the same error

**Comment by AlexCheema** [comment]
What device are you running on?

I see you're using conda, which might be causing issues since I believe tinygrad doesn't support conda
