### ISSUE TITLE
Showing 0 TFLOPS for Linux (Ubuntu 22.04, Quadro RTX 4000) + CUDA out of memory error on Llama 3.1 8B

### ISSUE THREAD

**Issue by fullofcaffeine** [exo-explore/exo#235]
Hi!

I managed to make Llama 3.1 8B to work across the two nodes (Linux Box 64GB of RAM + Quadro RTX 4000 (8GB) + 64GB of RAM and a Mac M2 with 32GB of RAM), as I can chat with it using the Tinychat instance on my Mac. However, it almost looks like (ironically) all the work is being done by the Linux CUDA node, and I had an OOM error.

First, the 0 TFLOPs issue:

<img width="899" alt="Screenshot 2024-09-25 at 6 11 34 p m" src="https://github.com/user-attachments/assets/899e1ea5-1f10-426b-a1fc-016c4b1254c7">

And the OOM error on the Linux box:

```
RuntimeError: CUDA Error 2, out of memory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fullofcaffeine/workspace/code/exo/exo/orchestration/standard_node.py", line 211, in _process_tensor
    result, inference_state, is_finished = await self.inference_engine.infer_tensor(request_id, shard, tensor, inference_state=inference_state)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fullofcaffeine/workspace/code/exo/exo/inference/tinygrad/inference.py", line 79, in infer_tensor
    await self.ensure_shard(shard)
  File "/home/fullofcaffeine/workspace/code/exo/exo/inference/tinygrad/inference.py", line 100, in ensure_shard
    self.model = await asyncio.get_event_loop().run_in_executor(self.executor, build_transformer, model_path, shard, "8B" if "8b" in shard.model_id.lower() else "70B")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fullofcaffeine/workspace/code/exo/exo/inference/tinygrad/inference.py", line 51, in build_transformer
    load_state_dict(model, weights, strict=False, consume=False)  # consume=True
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fullofcaffeine/workspace/code/exo/.venv/lib/python3.12/site-packages/tinygrad/nn/state.py", line 129, in load_state_dict
    else: v.replace(state_dict[k].to(v.device)).realize()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fullofcaffeine/workspace/code/exo/.venv/lib/python3.12/site-packages/tinygrad/tensor.py", line 3500, in _wrapper
    ret = fn(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/fullofcaffeine/workspace/code/exo/.venv/lib/python3.12/site-packages/tinygrad/tensor.py", line 213, in realize
    run_schedule(*self.schedule_with_vars(*lst), do_update_stats=do_update_stats)
  File "/home/fullofcaffeine/workspace/code/exo/.venv/lib/python3.12/site-packages/tinygrad/engine/realize.py", line 224, in run_schedule
    ei.run(var_vals, do_update_stats=do_update_stats)
  File "/home/fullofcaffeine/workspace/code/exo/.venv/lib/python3.12/site-packages/tinygrad/engine/realize.py", line 173, in run
    bufs = [cast(Buffer, x) for x in self.bufs] if jit else [cast(Buffer, x).ensure_allocated() for x in self.bufs]
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fullofcaffeine/workspace/code/exo/.venv/lib/python3.12/site-packages/tinygrad/device.py", line 77, in ensure_allocated
    def ensure_allocated(self) -> Buffer: return self.allocate() if not hasattr(self, '_buf') else self
                                                 ^^^^^^^^^^^^^^^
  File "/home/fullofcaffeine/workspace/code/exo/.venv/lib/python3.12/site-packages/tinygrad/device.py", line 86, in allocate
    self._buf = opaque if opaque is not None else self.allocator.alloc(self.nbytes, self.options)
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fullofcaffeine/workspace/code/exo/.venv/lib/python3.12/site-packages/tinygrad/device.py", line 155, in alloc
    return super().alloc(size, options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fullofcaffeine/workspace/code/exo/.venv/lib/python3.12/site-packages/tinygrad/device.py", line 136, in alloc
    return self._alloc(size, options if options is not None else BufferOptions())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fullofcaffeine/workspace/code/exo/.venv/lib/python3.12/site-packages/tinygrad/runtime/ops_cuda.py", line 68, in _alloc
    return init_c_var(cuda.CUdeviceptr(), lambda x: check(cuda.cuMemAlloc_v2(ctypes.byref(x), size)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fullofcaffeine/workspace/code/exo/.venv/lib/python3.12/site-packages/tinygrad/helpers.py", line 325, in init_c_var
    def init_c_var(ctypes_var, creat_cb): return (creat_cb(ctypes_var), ctypes_var)[1]
                                                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/fullofcaffeine/workspace/code/exo/.venv/lib/python3.12/site-packages/tinygrad/runtime/ops_cuda.py", line 68, in <lambda>
    return init_c_var(cuda.CUdeviceptr(), lambda x: check(cuda.cuMemAlloc_v2(ctypes.byref(x), size)))
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fullofcaffeine/workspace/code/exo/.venv/lib/python3.12/site-packages/tinygrad/runtime/ops_cuda.py", line 13, in check
    if status != 0: raise RuntimeError(f"CUDA Error {status}, {ctypes.string_at(init_c_var(ctypes.POINTER(ctypes.c_char)(), lambda x: cuda.cuGetErrorString(status, ctypes.byref(x)))).decode()}")  # noqa: E501
```

My questions:

1. How do I check if the Mac node is being used so that RAM usage is spread? I thought 8B would be fine to run in Quadro + the Mac M2 would be more than enough to run it.
2. Is the OOM a bug or is it expected?  Should I instead not use CUDA so that exo instead uses the 64GB of RAM? Is RAM more important than having CUDA in this case?
3. Why is exo showing 0TFLOPs for the Linux box?

Thanks in advance!

**Comment by HysenX-LI** [comment]
Because its FLOPS display is done by querying a text that records the performance of some known chip. For unknown chip display is 0

**Comment by pediegoivan** [comment]
Make sure CUDA and torch are happy on that node and that TFLOPS are measured before trying to run it

**Comment by fullofcaffeine** [comment]
OK, I'll further troubleshoot CUDA and torch and report any findings here. Thanks!

**Comment by cawdery87** [comment]
I am also experiencing this with a Quadro P5000. (0.0 TFLOPS)

**Comment by ForbiddenEra** [comment]
I'm getting this when trying to run even a 1B model on a 3060 12GB (which is device 1, my 2070S 8GB is device 0, had to set it in `exo/topology/device_capabilities.py` to show the 3060; also seems to make it use it as well, since I see memory usage go up to about 2.5gb before it dies on the 3060, with about 1.25gb using dedicated and 1.25gb using shared.

Note that I could at least say Hi and get a few messages back on both 1B and 3B using CLANG only (~12gb and 30gb usage each)
