### ISSUE TITLE
AttributeError: module 'math' has no attribute 'cbrt' when running the exo command

### ISSUE THREAD

**Issue by owen198** [exo-explore/exo#367]
I'm encountering an error when trying to run the `exo` command after installing the project. The specific error message is:

```
# exo

  _____  _____  
 / _ \ \/ / _ \ 
|  __/>  < (_) |
 \___/_/\_\___/ 
    
Detected system: Linux
Using inference engine: TinygradDynamicShardInferenceEngine with shard downloader: HFShardDownloader
[62198, 61519, 59494, 54267]
Chat interface started:
 - http://192.168.0.140:8000
 - http://172.17.0.1:8000
 - http://127.0.0.1:8000
 - http://10.232.201.88:8000
ChatGPT API endpoint served at:
 - http://192.168.0.140:8000/v1/chat/completions
 - http://172.17.0.1:8000/v1/chat/completions
 - http://127.0.0.1:8000/v1/chat/completions
 - http://10.232.201.88:8000/v1/chat/completions
Traceback (most recent call last):
  File "/usr/local/bin/exo", line 33, in <module>
    sys.exit(load_entry_point('exo', 'console_scripts', 'exo')())
  File "/usr/local/bin/exo", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/owen/workspace_ext/exo/exo/main.py", line 81, in <module>
    topology_viz = TopologyViz(chatgpt_api_endpoints=chatgpt_api_endpoints, web_chat_urls=web_chat_urls) if not args.disable_tui else None
  File "/home/owen/workspace_ext/exo/exo/viz/topology_viz.py", line 33, in __init__
    self.main_panel = Panel(self._generate_main_layout(), title="Exo Cluster (0 nodes)", border_style="bright_yellow")
  File "/home/owen/workspace_ext/exo/exo/viz/topology_viz.py", line 164, in _generate_main_layout
    bar_pos = (math.tanh(math.cbrt(total_flops)/2.5 - 2) + 1)
AttributeError: module 'math' has no attribute 'cbrt'
```

OS: Ubuntu 20.04
Python Version: 3.10.22

Would it be possible to update the code to handle this?
Thank you for your assistance!

**Comment by AlexCheema** [comment]
exo only supports Python >= 3.12

**Comment by owen198** [comment]
Thanks, really helpful!!!!

```
# exo
                                __      
                               /\ \__   
 __  __     __     __      ____\ \ ,_\  
/\ \/\ \  /'__`\ /'__`\   /',__\\ \ \/  
\ \ \_\ \/\  __//\ \L\.\_/\__, `\\ \ \_ 
 \/`____ \ \____\ \__/.\_\/\____/ \ \__\
  `/___/> \/____/\/__/\/_/\/___/   \/__/
     /\___/                             
     \/__/                              
                                                                       
               __                                                      
   __   _____ /\_\     __      __    ___     ___     ___ ___      __   
 /'__`\/\ '__`\/\ \  /'_ `\  /'__`\/' _ `\  / __`\ /' __` __`\  /'__`\ 
/\  __/\ \ \L\ \ \ \/\ \L\ \/\  __//\ \/\ \/\ \L\ \/\ \/\ \/\ \/\  __/ 
\ \____\\ \ ,__/\ \_\ \____ \ \____\ \_\ \_\ \____/\ \_\ \_\ \_\ \____\
 \/____/ \ \ \/  \/_/\/___L\ \/____/\/_/\/_/\/___/  \/_/\/_/\/_/\/____/
          \ \_\        /\____/                                         
           \/_/        \_/__/                                          
                                        __        __     
                      __               /\ \__    /\ \    
 _____   _ __   ___  /\_\     __    ___\ \ ,_\   \ \ \   
/\ '__`\/\`'__\/ __`\\/\ \  /'__`\ /'___\ \ \/    \ \ \  
\ \ \L\ \ \ \//\ \L\ \\ \ \/\  __//\ \__/\ \ \_    \ \_\ 
 \ \ ,__/\ \_\\ \____/_\ \ \ \____\ \____\\ \__\    \/\_\
  \ \ \/  \/_/ \/___//\ \_\ \/____/\/____/ \/__/     \/_/
   \ \_\             \ \____/                            
    \/_/              \/___/                             

Author: Prashant Kumar Kuntala
Version: 0.1.2
Usage: exo --help 
```
