### ISSUE TITLE
Unable to perform inference using NVIDIA devices and tinygrad

### ISSUE THREAD

**Issue by samheutmaker** [exo-explore/exo#44]
I'm running exo using a 4090 and a 3090 that exist on the same network. The devices can discover eachother just fine but are unable to perform inference using tinygrad.

Here is a video demonstrating the failure on a clean install of the latest version of exo.

Request:
```.bash
curl http://100.68.16.19:8000/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
     "model": "llama-3-8b",
     "messages": [{"role": "user", "content": "What is the meaning of exo?"}],
     "temperature": 0.7
   }'
  ```

Logs:
```
{"detail": "Error processing prompt (see logs with DEBUG>=2): compile failed: <null>(20): error: more than one user-defined conversion from \"nv_bfloat16\" to \"half\" applies:\n            function \"__half::__half(float)\"\n/usr/include/cuda_fp16.hpp(214): here\n            function \"__half::__half(short)\"\n/usr/include/cuda_fp16.hpp(227): here\n            function \"__half::__half(unsigned short)\"\n/usr/include/cuda_fp16.hpp(228): here\n            function \"__half::__half(int)\"\n/usr/include/cuda_fp16.hpp(229): here\n            function \"__half::__half(unsigned int)\"\n/usr/include/cuda_fp16.hpp(230): here\n            function \"__half::__half(long long)\"\n/usr/include/cuda_fp16.hpp(231): here\n            function \"__half::__half(unsigned long long)\"\n/usr/include/cuda_fp16.hpp(232): here\n\n<null>(21): error: more than one user-defined conversion from \"nv_bfloat16\" to \"half\" applies:\n            function \"__half::__half(float)\"\n/usr/include/cuda_fp16.hpp(214): here\n            function \"__half::__half(short)\"\n/usr/include/cuda_fp16.hpp(227): here\n            function \"__half::__half(unsigned short)\"\n/usr/include/cuda_fp16.hpp(228): here\n            function \"__half::__half(int)\"\n/usr/include/cuda_fp16.hpp(229): here\n            function \"__half::__half(unsigned int)\"\n/usr/include/cuda_fp16.hpp(230): here\n            function \"__half::__half(long long)\"\n/usr/include/cuda_fp16.hpp(231): here\n            function \"__half::__half(unsigned long long)\"\n/usr/include/cuda_fp16.hpp(232): here\n\n<null>(22): error: more than one user-defined conversion from \"nv_bfloat16\" to \"half\" applies:\n            function \"__half::__half(float)\"\n/usr/include/cuda_fp16.hpp(214): here\n            function \"__half::__half(short)\"\n/usr/include/cuda_fp16.hpp(227): here\n            function \"__half::__half(unsigned short)\"\n/usr/include/cuda_fp16.hpp(228): here\n            function \"__half::__half(int)\"\n/usr/include/cuda_fp16.hpp(229): here\n            function \"__half::__half(unsigned int)\"\n/usr/include/cuda_fp16.hpp(230): here\n            function \"__half::__half(long long)\"\n/usr/include/cuda_fp16.hpp(231): here\n            function \"__half::__half(unsigned long long)\"\n/usr/include/cuda_fp16.hpp(232): here\n\n<null>(23): error: more than one user-defined conversion from \"nv_bfloat16\" to \"half\" applies:\n            function \"__half::__half(float)\"\n/usr/include/cuda_fp16.hpp(214): here\n            function \"__half::__half(short)\"\n/usr/include/cuda_fp16.hpp(227): here\n            function \"__half::__half(unsigned short)\"\n/usr/include/cuda_fp16.hpp(228): here\n            function \"__half::__half(int)\"\n/usr/include/cuda_fp16.hpp(229): here\n            function \"__half::__half(unsigned int)\"\n/usr/include/cuda_fp16.hpp(230): here\n            function \"__half::__half(long long)\"\n/usr/include/cuda_fp16.hpp(231): here\n            function \"__half::__half(unsigned long long)\"\n/usr/include/cuda_fp16.hpp(232): here\n\n4 errors detected in the compilation of \"<null>\".\n\u0000"}
```

**Comment by elsatch** [comment]
I got the same error today with 2 nodes and 1 node arrangements, performing the base example:

```
{"detail": "Error processing prompt (see logs with DEBUG>=2): compile failed: <null>(20): error: more than one user-defined conversion from \"nv_bfloat16\" to \"half\" applies:\n            function \"__half::__half(float)\" (declared at line 201 of /usr/local/cuda/include/cuda_fp16.hpp)\n            function \"__half::__half(short)\" (declared at line 214 of /usr/local/cuda/include/cuda_fp16.hpp)\n            function \"__half::__half(unsigned short)\" (declared at line 215 of /usr/local/cuda/include/cuda_fp16.hpp)\n
   function \"__half::__half(int)\" (declared at line 216 of /usr/local/cuda/include/cuda_fp16.hpp)\n            function \"__half::__half(unsigned int)\" (declared at line 217 of /usr/local/cuda/include/cuda_fp16.hpp)\n            function \"__half::__half(long long)\" (declared at line 218 of /usr/local/cuda/include/cuda_fp16.hpp)\n            function \"__half::__half(unsigned long long)\" (declared at line 219 of /usr/local/cuda/include/cuda_fp16.hpp)\n    data0[alu1] = (half)(val0);\n                        ^\n\n<null>(21): error: more than one user-defined conversion from \"nv_bfloat16\" to \"half\" applies:\n            function \"__half::__half(float)\" (declared at line 201 of /usr/local/cuda/include/cuda_fp16.hpp)\n            function \"__half::__half(short)\" (declared at line 214 of /usr/local/cuda/include/cuda_fp16.hpp)\n            function \"__half::__half(unsigned short)\" (declared at line 215 of /usr/local/cuda/include/cuda_fp16.hpp)\n            function \"__half::__half(int)\" (declared at line 216 of /usr/local/cuda/include/cuda_fp16.hpp)\n            function \"__half::__half(unsigned int)\" (declared at line 217 of /usr/local/cuda/include/cuda_fp16.hpp)\n            function \"__half::__half(long long)\" (declared at line 218 of /usr/local/cuda/include/cuda_fp16.hpp)\n            function \"__half::__half(unsigned long long)\" (declared at line 219 of /usr/local/cuda/include/cuda_fp16.hpp)\n    data0[alu2] = (half)(val1);\n                        ^\n\n<null>(22): error: more than one user-defined conversion from \"nv_bfloat16\" to \"half\" applies:\n            function \"__half::__half(float)\" (declared at line 201 of /usr/local/cuda/include/cuda_fp16.hpp)\n            function \"__half::__half(short)\" (declared at line 214 of /usr/local/cuda/include/cuda_fp16.hpp)\n            function \"__half::__half(unsigned short)\" (declared at line 215 of /usr/local/cuda/include/cuda_fp16.hpp)\n            function \"__half::__half(int)\" (declared at line 216 of /usr/local/cuda/include/cuda_fp16.hpp)\n            function \"__half::__half(unsigned int)\" (declared at line 217 of /usr/local/cuda/include/cuda_fp16.hpp)\n            function \"__half::__half(long long)\" (declared at line 218 of /usr/local/cuda/include/cuda_fp16.hpp)\n            function \"__half::__half(unsigned long long)\" (declared at line 219 of /usr/local/cuda/include/cuda_fp16.hpp)\n    data0[alu3] = (half)(val2);\n                        ^\n\n<null>(23): error: more than one user-defined conversion from \"nv_bfloat16\" to \"half\" applies:\n            function \"__half::__half(float)\" (declared at line 201 of /usr/local/cuda/include/cuda_fp16.hpp)\n            function \"__half::__half(short)\" (declared at line 214 of /usr/local/cuda/include/cuda_fp16.hpp)\n
 function \"__half::__half(unsigned short)\" (declared at line 215 of /usr/local/cuda/include/cuda_fp16.hpp)\n            function \"__half::__half(int)\" (declared at line 216 of /usr/local/cuda/include/cuda_fp16.hpp)\n            function \"__half::__half(unsigned int)\" (declared at line 217 of /usr/local/cuda/include/cuda_fp16.hpp)\n            function \"__half::__half(long long)\" (declared at line 218 of /usr/local/cuda/include/cuda_fp16.hpp)\n            function \"__half::__half(unsigned long long)\" (declared at line 219 of /usr/local/cuda/include/cuda_fp16.hpp)\n    data0[alu0] = (half)(val3);\n                        ^\n\n4 errors detected in the compilation of \"<null>\".\n\u0000"}
 ```

**Comment by deezed420** [comment]
I think you have to use WSL for tinygrad

**Comment by lucaricciatl** [comment]
Same error here on Linux.
`Detected system: Linux
Inference engine name after selection: tinygrad
Using inference engine: TinygradDynamicShardInferenceEngine with shard downloader: HFShardDownloader
[52801, 55127, 50627, 64073, 62011, 59086, 52305, 57701, 56768, 52356, 53546, 56919, 52123, 58252, 62609, 57445, 57668]
Chat interface started:
 - http://10.8.0.10:52415
 - http://127.0.0.1:52415
 - http://192.168.1.175:52415
ChatGPT API endpoint served at:
 - http://10.8.0.10:52415/v1/chat/completions
 - http://127.0.0.1:52415/v1/chat/completions
 - http://192.168.1.175:52415/v1/chat/completions
has_read=True, has_write=True
Processing prompt: <|begin_of_text|><|start_header_id|>system<|end_header_id|>

Cutting Knowledge Date: December 2023
Today Date: 06 Jan 2025

<|eot_id|><|start_header_id|>user<|end_header_id|>

What is the meaning of exo?<|eot_id|><|start_header_id|>assistant<|end_header_id|>


Removing download task for Shard(model_id='llama-3.2-3b', start_layer=0, end_layer=27, n_layers=28): True
  0%|                                                                                                                | 0/256 [00:00<?, ?it/s]
loaded weights in 140.11 ms, 0.02 GB loaded at 0.13 GB/s
Error processing prompt: Nvrtc Error 6, NVRTC_ERROR_COMPILATION
<null>(14): error: more than one user-defined conversion from "nv_bfloat16" to "half" applies:
            function "__half::__half(float)"
/usr/include/cuda_fp16.hpp(214): here
            function "__half::__half(short)"
/usr/include/cuda_fp16.hpp(227): here
            function "__half::__half(unsigned short)"
/usr/include/cuda_fp16.hpp(228): here
            function "__half::__half(int)"
/usr/include/cuda_fp16.hpp(229): here
            function "__half::__half(unsigned int)"
/usr/include/cuda_fp16.hpp(230): here
            function "__half::__half(long long)"
/usr/include/cuda_fp16.hpp(231): here
            function "__half::__half(unsigned long long)"
/usr/include/cuda_fp16.hpp(232): here

<null>(14): error: more than one user-defined conversion from "nv_bfloat16" to "half" applies:
            function "__half::__half(float)"
/usr/include/cuda_fp16.hpp(214): here
            function "__half::__half(short)"
/usr/include/cuda_fp16.hpp(227): here
            function "__half::__half(unsigned short)"
/usr/include/cuda_fp16.hpp(228): here
            function "__half::__half(int)"
/usr/include/cuda_fp16.hpp(229): here
            function "__half::__half(unsigned int)"
/usr/include/cuda_fp16.hpp(230): here
            function "__half::__half(long long)"
/usr/include/cuda_fp16.hpp(231): here
            function "__half::__half(unsigned long long)"
/usr/include/cuda_fp16.hpp(232): here

<null>(14): error: more than one user-defined conversion from "nv_bfloat16" to "half" applies:
            function "__half::__half(float)"
/usr/include/cuda_fp16.hpp(214): here
            function "__half::__half(short)"
/usr/include/cuda_fp16.hpp(227): here
            function "__half::__half(unsigned short)"
/usr/include/cuda_fp16.hpp(228): here
            function "__half::__half(int)"
/usr/include/cuda_fp16.hpp(229): here
            function "__half::__half(unsigned int)"
/usr/include/cuda_fp16.hpp(230): here
            function "__half::__half(long long)"
/usr/include/cuda_fp16.hpp(231): here
            function "__half::__half(unsigned long long)"
/usr/include/cuda_fp16.hpp(232): here

<null>(14): error: more than one user-defined conversion from "nv_bfloat16" to "half" applies:
            function "__half::__half(float)"
/usr/include/cuda_fp16.hpp(214): here
            function "__half::__half(short)"
/usr/include/cuda_fp16.hpp(227): here
            function "__half::__half(unsigned short)"
/usr/include/cuda_fp16.hpp(228): here
            function "__half::__half(int)"
/usr/include/cuda_fp16.hpp(229): here
            function "__half::__half(unsigned int)"
/usr/include/cuda_fp16.hpp(230): here
            function "__half::__half(long long)"
/usr/include/cuda_fp16.hpp(231): here
            function "__half::__half(unsigned long long)"
/usr/include/cuda_fp16.hpp(232): here

4 errors detected in the compilation of "<null>".

Traceback (most recent call last):
  File "/home/atled/app/exo/.venv/lib/python3.12/site-packages/exo-0.0.1-py3.12.egg/exo/main.py", line 205, in run_model_cli
    await node.process_prompt(shard, prompt, request_id=request_id)
  File "/home/atled/app/exo/.venv/lib/python3.12/site-packages/exo-0.0.1-py3.12.egg/exo/orchestration/node.py", line 163, in process_prompt
    resp = await self._process_prompt(base_shard, prompt, request_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atled/app/exo/.venv/lib/python3.12/site-packages/exo-0.0.1-py3.12.egg/exo/orchestration/node.py", line 197, in _process_prompt
    result = await self.inference_engine.infer_prompt(request_id, shard, prompt)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atled/app/exo/.venv/lib/python3.12/site-packages/exo-0.0.1-py3.12.egg/exo/inference/inference_engine.py", line 43, in 
infer_prompt
    tokens = await self.encode(shard, prompt)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atled/app/exo/.venv/lib/python3.12/site-packages/exo-0.0.1-py3.12.egg/exo/inference/tinygrad/inference.py", line 88, in encode
    await self.ensure_shard(shard)
  File "/home/atled/app/exo/.venv/lib/python3.12/site-packages/exo-0.0.1-py3.12.egg/exo/inference/tinygrad/inference.py", line 151, in 
ensure_shard
    model_shard = await loop.run_in_executor(self.executor, build_transformer, model_path, shard, parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atled/miniconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atled/app/exo/.venv/lib/python3.12/site-packages/exo-0.0.1-py3.12.egg/exo/inference/tinygrad/inference.py", line 59, in 
build_transformer
    load_state_dict(model, weights, strict=False, consume=False)  # consume=True
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atled/app/exo/.venv/lib/python3.12/site-packages/tinygrad/nn/state.py", line 131, in load_state_dict
    else: v.replace(state_dict[k].to(v.device)).realize()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atled/app/exo/.venv/lib/python3.12/site-packages/tinygrad/tensor.py", line 3754, in _wrapper
    ret = fn(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/atled/app/exo/.venv/lib/python3.12/site-packages/tinygrad/tensor.py", line 219, in realize
    run_schedule(*self.schedule_with_vars(*lst), do_update_stats=do_update_stats)
  File "/home/atled/app/exo/.venv/lib/python3.12/site-packages/tinygrad/engine/realize.py", line 215, in run_schedule
    for ei in lower_schedule(schedule):
  File "/home/atled/app/exo/.venv/lib/python3.12/site-packages/tinygrad/engine/realize.py", line 208, in lower_schedule
    raise e
  File "/home/atled/app/exo/.venv/lib/python3.12/site-packages/tinygrad/engine/realize.py", line 202, in lower_schedule
    try: yield lower_schedule_item(si)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atled/app/exo/.venv/lib/python3.12/site-packages/tinygrad/engine/realize.py", line 187, in lower_schedule_item
    runner = get_runner(si.outputs[0].device, si.ast)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atled/app/exo/.venv/lib/python3.12/site-packages/tinygrad/engine/realize.py", line 155, in get_runner
    method_cache[ckey] = method_cache[bkey] = ret = CompiledRunner(replace(prg, device=device))
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atled/app/exo/.venv/lib/python3.12/site-packages/tinygrad/engine/realize.py", line 81, in __init__
    self.lib:bytes = precompiled if precompiled is not None else Device[p.device].compiler.compile_cached(p.src)
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atled/app/exo/.venv/lib/python3.12/site-packages/tinygrad/device.py", line 194, in compile_cached
    lib = self.compile(src)
          ^^^^^^^^^^^^^^^^^
  File "/home/atled/app/exo/.venv/lib/python3.12/site-packages/tinygrad/runtime/support/compiler_cuda.py", line 63, in compile
    def compile(self, src:str) -> bytes: return self._compile_program(src, nvrtc.nvrtcGetCUBIN, nvrtc.nvrtcGetCUBINSize)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atled/app/exo/.venv/lib/python3.12/site-packages/tinygrad/runtime/support/compiler_cuda.py", line 49, in _compile_program
    nvrtc_check(nvrtc.nvrtcCompileProgram(prog, len(self.compile_options), to_char_p_p([o.encode() for o in self.compile_options])), prog)
  File "/home/atled/app/exo/.venv/lib/python3.12/site-packages/tinygrad/runtime/support/compiler_cuda.py", line 16, in nvrtc_check
    raise CompileError(f"Nvrtc Error {status}, {ctypes.string_at(nvrtc.nvrtcGetErrorString(status)).decode()}\n{err_log}")
tinygrad.device.CompileError: Nvrtc Error 6, NVRTC_ERROR_COMPILATION
<null>(14): error: more than one user-defined conversion from "nv_bfloat16" to "half" applies:
            function "__half::__half(float)"
/usr/include/cuda_fp16.hpp(214): here
            function "__half::__half(short)"
/usr/include/cuda_fp16.hpp(227): here
            function "__half::__half(unsigned short)"
/usr/include/cuda_fp16.hpp(228): here
            function "__half::__half(int)"
/usr/include/cuda_fp16.hpp(229): here
            function "__half::__half(unsigned int)"
/usr/include/cuda_fp16.hpp(230): here
            function "__half::__half(long long)"
/usr/include/cuda_fp16.hpp(231): here
            function "__half::__half(unsigned long long)"
/usr/include/cuda_fp16.hpp(232): here

<null>(14): error: more than one user-defined conversion from "nv_bfloat16" to "half" applies:
            function "__half::__half(float)"
/usr/include/cuda_fp16.hpp(214): here
            function "__half::__half(short)"
/usr/include/cuda_fp16.hpp(227): here
            function "__half::__half(unsigned short)"
/usr/include/cuda_fp16.hpp(228): here
            function "__half::__half(int)"
/usr/include/cuda_fp16.hpp(229): here
            function "__half::__half(unsigned int)"
/usr/include/cuda_fp16.hpp(230): here
            function "__half::__half(long long)"
/usr/include/cuda_fp16.hpp(231): here
            function "__half::__half(unsigned long long)"
/usr/include/cuda_fp16.hpp(232): here

<null>(14): error: more than one user-defined conversion from "nv_bfloat16" to "half" applies:
            function "__half::__half(float)"
/usr/include/cuda_fp16.hpp(214): here
            function "__half::__half(short)"
/usr/include/cuda_fp16.hpp(227): here
            function "__half::__half(unsigned short)"
/usr/include/cuda_fp16.hpp(228): here
            function "__half::__half(int)"
/usr/include/cuda_fp16.hpp(229): here
            function "__half::__half(unsigned int)"
/usr/include/cuda_fp16.hpp(230): here
            function "__half::__half(long long)"
/usr/include/cuda_fp16.hpp(231): here
            function "__half::__half(unsigned long long)"
/usr/include/cuda_fp16.hpp(232): here

<null>(14): error: more than one user-defined conversion from "nv_bfloat16" to "half" applies:
            function "__half::__half(float)"
/usr/include/cuda_fp16.hpp(214): here
            function "__half::__half(short)"
/usr/include/cuda_fp16.hpp(227): here
            function "__half::__half(unsigned short)"
/usr/include/cuda_fp16.hpp(228): here
            function "__half::__half(int)"
/usr/include/cuda_fp16.hpp(229): here
            function "__half::__half(unsigned int)"
/usr/include/cuda_fp16.hpp(230): here
            function "__half::__half(long long)"
/usr/include/cuda_fp16.hpp(231): here
            function "__half::__half(unsigned long long)"
/usr/include/cuda_fp16.hpp(232): here

4 errors detected in the compilation of "<null>".

Received exit signal SIGTERM...

**Comment by divinity76** [comment]
can you check if https://github.com/exo-explore/exo/pull/684 fixes it?

**Comment by divinity76** [comment]
#684 has been merged, can you check if it's still happening in git master?

**Comment by lucaricciatl** [comment]
Yes, let me check on master

**Comment by lucaricciatl** [comment]
I cannot reproduce the error

**Comment by rltakashige** [comment]
Please reraise if this is still an issue in EXO 1.0
