### ISSUE TITLE
exo installation & configuration issue in windows 11

### ISSUE THREAD

**Issue by isureshsubramanian** [exo-explore/exo#455]
I am getting the below error . I am trying to add my windows laptop with below configuration in existing exo cluster running in Mac. Any help would be appreciated.

My laptop configuration is below

1. Windows 11
2. NVIDIA GeForce RTX 2060
3. NVIDIA-SMI 566.14 
4. Driver Version: 566.14 
5. CUDA Version: 12.7

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Sep_12_02:55:00_Pacific_Daylight_Time_2024
Cuda compilation tools, release 12.6, V12.6.77
Build cuda_12.6.r12.6/compiler.34841621_0

Cancelling 0 outstanding tasks
Traceback (most recent call last):
  File "\\?\C:\Users\ISure\.conda\envs\exo_env\Scripts\exo-script.py", line 33, in <module>
    sys.exit(load_entry_point('exo', 'console_scripts', 'exo')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\workspace\exo\exo\main.py", line 233, in run
    loop.run_until_complete(main())
  File "C:\Users\ISure\.conda\envs\exo_env\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "d:\workspace\exo\exo\main.py", line 214, in main
    loop.add_signal_handler(s, handle_exit)
  File "C:\Users\ISure\.conda\envs\exo_env\Lib\asyncio\events.py", line 582, in add_signal_handler
    raise NotImplementedError
NotImplementedError

**Comment by lstrozzi** [comment]
Same issue here. I installed python with:
conda create -n exo python=3.17
Result: C:\Users\xxxxx\source\repos\exo>python --version
Python 3.12.7

Same error:
File "C:\Users\luca_\miniconda3\envs\exo\Lib\site-packages\exo\main.py", line 214, in main
    loop.add_signal_handler(s, handle_exit)
  File "C:\Users\luca_\miniconda3\envs\exo\Lib\asyncio\events.py", line 582, in add_signal_handler
    raise NotImplementedError

I tried in Windows, in WSL2 Ubuntu, nothing works at all, different errors same result.

**Comment by VGLALALA** [comment]
WSL wont work, even if you install properly, the networking you will be problematic

**Comment by RikuKunMS2** [comment]
You can get it to work with WSL2, if you enable mirror mode networking in the .wslconfig

Go to your user folder on windows, add a file called '.wslconfig' if it doesn't exist already 

then inside make sure it contains

`[wsl2]
networkingMode=mirrored`

**Comment by VGLALALA** [comment]
seems like a very credible solution, thanks!

**Comment by Youho99** [comment]
`(exo) youho@DESKTOP-SIT8KRN:~$ exo
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Selected inference engine: None

  _____  _____
 / _ \ \/ / _ \
|  __/>  < (_) |
 \___/_/\_\___/

Detected system: Linux
Inference engine name after selection: tinygrad
Traceback (most recent call last):
  File "/home/youho/miniconda3/envs/exo/bin/exo", line 33, in <module>
    sys.exit(load_entry_point('exo', 'console_scripts', 'exo')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/youho/miniconda3/envs/exo/bin/exo", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/youho/miniconda3/envs/exo/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/youho/miniconda3/envs/exo/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/youho/exo/exo/main.py", line 106, in <module>
    inference_engine = get_inference_engine(inference_engine_name, shard_downloader)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/youho/exo/exo/inference/inference_engine.py", line 69, in get_inference_engine
    from exo.inference.tinygrad.inference import TinygradDynamicShardInferenceEngine
  File "/home/youho/exo/exo/inference/tinygrad/inference.py", line 4, in <module>
    from exo.inference.tinygrad.models.llama import Transformer, TransformerShard, convert_from_huggingface, fix_bf16, sample_logits
  File "/home/youho/exo/exo/inference/tinygrad/models/llama.py", line 2, in <module>
    from tinygrad import Tensor, Variable, TinyJit, dtypes, nn, Device
  File "/home/youho/miniconda3/envs/exo/lib/python3.12/site-packages/tinygrad/__init__.py", line 5, in <module>
    from tinygrad.tensor import Tensor                                    # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/youho/miniconda3/envs/exo/lib/python3.12/site-packages/tinygrad/tensor.py", line 12, in <module>
    from tinygrad.device import Device, BufferSpec
  File "/home/youho/miniconda3/envs/exo/lib/python3.12/site-packages/tinygrad/device.py", line 226, in <module>
    class CPUProgram:
  File "/home/youho/miniconda3/envs/exo/lib/python3.12/site-packages/tinygrad/device.py", line 227, in CPUProgram
    helper_handle = ctypes.CDLL(ctypes.util.find_library('System' if OSX else 'kernel32' if sys.platform == "win32" else 'gcc_s'))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/youho/miniconda3/envs/exo/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /home/youho/miniconda3/envs/exo/lib/libgcc_s.so: invalid ELF header`

Don't run on WSL2
Even with the .wslconfig

**Comment by PaulShiLi** [comment]
> Don't run on WSL2 Even with the .wslconfig
> 
> ```
> None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
> None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
> Selected inference engine: None
> 
>   _____  _____
>  / _ \ \/ / _ \
> |  __/>  < (_) |
>  \___/_/\_\___/
> 
> Detected system: Linux
> Inference engine name after selection: tinygrad
> Traceback (most recent call last):
>   File "/home/youho/miniconda3/envs/exo/bin/exo", line 33, in <module>
>     sys.exit(load_entry_point('exo', 'console_scripts', 'exo')())
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/youho/miniconda3/envs/exo/bin/exo", line 25, in importlib_load_entry_point
>     return next(matches).load()
>            ^^^^^^^^^^^^^^^^^^^^
>   File "/home/youho/miniconda3/envs/exo/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
>     module = import_module(match.group('module'))
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/youho/miniconda3/envs/exo/lib/python3.12/importlib/__init__.py", line 90, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 999, in exec_module
>   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
>   File "/home/youho/exo/exo/main.py", line 106, in <module>
>     inference_engine = get_inference_engine(inference_engine_name, shard_downloader)
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/youho/exo/exo/inference/inference_engine.py", line 69, in get_inference_engine
>     from exo.inference.tinygrad.inference import TinygradDynamicShardInferenceEngine
>   File "/home/youho/exo/exo/inference/tinygrad/inference.py", line 4, in <module>
>     from exo.inference.tinygrad.models.llama import Transformer, TransformerShard, convert_from_huggingface, fix_bf16, sample_logits
>   File "/home/youho/exo/exo/inference/tinygrad/models/llama.py", line 2, in <module>
>     from tinygrad import Tensor, Variable, TinyJit, dtypes, nn, Device
>   File "/home/youho/miniconda3/envs/exo/lib/python3.12/site-packages/tinygrad/__init__.py", line 5, in <module>
>     from tinygrad.tensor import Tensor                                    # noqa: F401
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/youho/miniconda3/envs/exo/lib/python3.12/site-packages/tinygrad/tensor.py", line 12, in <module>
>     from tinygrad.device import Device, BufferSpec
>   File "/home/youho/miniconda3/envs/exo/lib/python3.12/site-packages/tinygrad/device.py", line 226, in <module>
>     class CPUProgram:
>   File "/home/youho/miniconda3/envs/exo/lib/python3.12/site-packages/tinygrad/device.py", line 227, in CPUProgram
>     helper_handle = ctypes.CDLL(ctypes.util.find_library('System' if OSX else 'kernel32' if sys.platform == "win32" else 'gcc_s'))
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/youho/miniconda3/envs/exo/lib/python3.12/ctypes/__init__.py", line 379, in __init__
>     self._handle = _dlopen(self._name, mode)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^
> OSError: /home/youho/miniconda3/envs/exo/lib/libgcc_s.so: invalid ELF header```
> ```

Getting the same error here as well:
  _____  _____
 / _ \ \/ / _ \
|  __/>  < (_) |
 \___/_/\_\___/

Detected system: Linux
Inference engine name after selection: tinygrad
Traceback (most recent call last):
  File "/home/sub01/miniconda3/bin/exo", line 33, in <module>
    sys.exit(load_entry_point('exo', 'console_scripts', 'exo')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sub01/miniconda3/bin/exo", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/sub01/miniconda3/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sub01/miniconda3/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/sub01/Apps/exo/exo/main.py", line 106, in <module>
    inference_engine = get_inference_engine(inference_engine_name, shard_downloader)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sub01/Apps/exo/exo/inference/inference_engine.py", line 69, in get_inference_engine
    from exo.inference.tinygrad.inference import TinygradDynamicShardInferenceEngine
  File "/home/sub01/Apps/exo/exo/inference/tinygrad/inference.py", line 4, in <module>
    from exo.inference.tinygrad.models.llama import Transformer, TransformerShard, convert_from_huggingface, fix_bf16, sample_logits
  File "/home/sub01/Apps/exo/exo/inference/tinygrad/models/llama.py", line 2, in <module>
    from tinygrad import Tensor, Variable, TinyJit, dtypes, nn, Device
  File "/home/sub01/miniconda3/lib/python3.12/site-packages/tinygrad/__init__.py", line 5, in <module>
    from tinygrad.tensor import Tensor                                    # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sub01/miniconda3/lib/python3.12/site-packages/tinygrad/tensor.py", line 12, in <module>
    from tinygrad.device import Device, BufferSpec
  File "/home/sub01/miniconda3/lib/python3.12/site-packages/tinygrad/device.py", line 226, in <module>
    class CPUProgram:
  File "/home/sub01/miniconda3/lib/python3.12/site-packages/tinygrad/device.py", line 227, in CPUProgram
    helper_handle = ctypes.CDLL(ctypes.util.find_library('System' if OSX else 'kernel32' if sys.platform == "win32" else 'gcc_s'))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sub01/miniconda3/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /home/sub01/miniconda3/lib/libgcc_s.so: invalid ELF header


I guess there's no windows support at all now that wsl 2 is broken.

**Comment by Youho99** [comment]
> > Don't run on WSL2 Even with the .wslconfig
> > 
> > ```
> > None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
> > None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
> > Selected inference engine: None
> > 
> >   _____  _____
> >  / _ \ \/ / _ \
> > |  __/>  < (_) |
> >  \___/_/\_\___/
> > 
> > Detected system: Linux
> > Inference engine name after selection: tinygrad
> > Traceback (most recent call last):
> >   File "/home/youho/miniconda3/envs/exo/bin/exo", line 33, in <module>
> >     sys.exit(load_entry_point('exo', 'console_scripts', 'exo')())
> >              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/home/youho/miniconda3/envs/exo/bin/exo", line 25, in importlib_load_entry_point
> >     return next(matches).load()
> >            ^^^^^^^^^^^^^^^^^^^^
> >   File "/home/youho/miniconda3/envs/exo/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
> >     module = import_module(match.group('module'))
> >              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/home/youho/miniconda3/envs/exo/lib/python3.12/importlib/__init__.py", line 90, in import_module
> >     return _bootstrap._gcd_import(name[level:], package, level)
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
> >   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
> >   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
> >   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
> >   File "<frozen importlib._bootstrap_external>", line 999, in exec_module
> >   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
> >   File "/home/youho/exo/exo/main.py", line 106, in <module>
> >     inference_engine = get_inference_engine(inference_engine_name, shard_downloader)
> >                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/home/youho/exo/exo/inference/inference_engine.py", line 69, in get_inference_engine
> >     from exo.inference.tinygrad.inference import TinygradDynamicShardInferenceEngine
> >   File "/home/youho/exo/exo/inference/tinygrad/inference.py", line 4, in <module>
> >     from exo.inference.tinygrad.models.llama import Transformer, TransformerShard, convert_from_huggingface, fix_bf16, sample_logits
> >   File "/home/youho/exo/exo/inference/tinygrad/models/llama.py", line 2, in <module>
> >     from tinygrad import Tensor, Variable, TinyJit, dtypes, nn, Device
> >   File "/home/youho/miniconda3/envs/exo/lib/python3.12/site-packages/tinygrad/__init__.py", line 5, in <module>
> >     from tinygrad.tensor import Tensor                                    # noqa: F401
> >     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/home/youho/miniconda3/envs/exo/lib/python3.12/site-packages/tinygrad/tensor.py", line 12, in <module>
> >     from tinygrad.device import Device, BufferSpec
> >   File "/home/youho/miniconda3/envs/exo/lib/python3.12/site-packages/tinygrad/device.py", line 226, in <module>
> >     class CPUProgram:
> >   File "/home/youho/miniconda3/envs/exo/lib/python3.12/site-packages/tinygrad/device.py", line 227, in CPUProgram
> >     helper_handle = ctypes.CDLL(ctypes.util.find_library('System' if OSX else 'kernel32' if sys.platform == "win32" else 'gcc_s'))
> >                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/home/youho/miniconda3/envs/exo/lib/python3.12/ctypes/__init__.py", line 379, in __init__
> >     self._handle = _dlopen(self._name, mode)
> >                    ^^^^^^^^^^^^^^^^^^^^^^^^^
> > OSError: /home/youho/miniconda3/envs/exo/lib/libgcc_s.so: invalid ELF header```
> > ```
> 
> Getting the same error here as well:
>   _____  _____
>  / _ \ \/ / _ \
> |  __/>  < (_) |
>  \___/_/\_\___/
> 
> Detected system: Linux
> Inference engine name after selection: tinygrad
> Traceback (most recent call last):
>   File "/home/sub01/miniconda3/bin/exo", line 33, in <module>
>     sys.exit(load_entry_point('exo', 'console_scripts', 'exo')())
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/sub01/miniconda3/bin/exo", line 25, in importlib_load_entry_point
>     return next(matches).load()
>            ^^^^^^^^^^^^^^^^^^^^
>   File "/home/sub01/miniconda3/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
>     module = import_module(match.group('module'))
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/sub01/miniconda3/lib/python3.12/importlib/__init__.py", line 90, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 999, in exec_module
>   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
>   File "/home/sub01/Apps/exo/exo/main.py", line 106, in <module>
>     inference_engine = get_inference_engine(inference_engine_name, shard_downloader)
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/sub01/Apps/exo/exo/inference/inference_engine.py", line 69, in get_inference_engine
>     from exo.inference.tinygrad.inference import TinygradDynamicShardInferenceEngine
>   File "/home/sub01/Apps/exo/exo/inference/tinygrad/inference.py", line 4, in <module>
>     from exo.inference.tinygrad.models.llama import Transformer, TransformerShard, convert_from_huggingface, fix_bf16, sample_logits
>   File "/home/sub01/Apps/exo/exo/inference/tinygrad/models/llama.py", line 2, in <module>
>     from tinygrad import Tensor, Variable, TinyJit, dtypes, nn, Device
>   File "/home/sub01/miniconda3/lib/python3.12/site-packages/tinygrad/__init__.py", line 5, in <module>
>     from tinygrad.tensor import Tensor                                    # noqa: F401
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/sub01/miniconda3/lib/python3.12/site-packages/tinygrad/tensor.py", line 12, in <module>
>     from tinygrad.device import Device, BufferSpec
>   File "/home/sub01/miniconda3/lib/python3.12/site-packages/tinygrad/device.py", line 226, in <module>
>     class CPUProgram:
>   File "/home/sub01/miniconda3/lib/python3.12/site-packages/tinygrad/device.py", line 227, in CPUProgram
>     helper_handle = ctypes.CDLL(ctypes.util.find_library('System' if OSX else 'kernel32' if sys.platform == "win32" else 'gcc_s'))
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/sub01/miniconda3/lib/python3.12/ctypes/__init__.py", line 379, in __init__
>     self._handle = _dlopen(self._name, mode)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^
> OSError: /home/sub01/miniconda3/lib/libgcc_s.so: invalid ELF header
> 
> 
> I guess there's no windows support at all now that wsl 2 is broken.

It finally run for me
Don't use conda env, but the venv given on the installation 
Too, i have the .wslconfig, but i don't test without, so i cannot say if it's important or not
