### ISSUE TITLE
Model type mllama not supported

### ISSUE THREAD

**Issue by chodorenko** [exo-explore/exo#477]
I try test Xkev/Llama-3.2V-11B-cot 

Error: Failed to fetch completions: Error processing prompt (see logs with DEBUG>=2): Model type mllama not supported.
    at Proxy.openaiChatCompletion (http://localhost:52415/index.js:375:17)
    at async Proxy.processMessage (http://localhost:52415/index.js:255:17)

**Comment by rltakashige** [comment]
Many MLX models are supported in EXO 1.0, but we're adding support for more - please raise an issue if you would still like this.
