### ISSUE TITLE
No module named `aiohttp`

### ISSUE THREAD

**Issue by troelsfr** [exo-explore/exo#7]
After following the instructions:
```
git clone git@github.com:exo-explore/exo.git
cd exo
virtualenv develop_env
source develop_env/bin/activate
 pip install -r requirements.txt
```
I get:
```
python3 main.py

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
0it [00:00, ?it/s]
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Traceback (most recent call last):
  File "/Users/tfr/Documents/TestArea/exo/main.py", line 14, in <module>
    from exo.api import ChatGPTAPI
  File "/Users/tfr/Documents/TestArea/exo/exo/api/__init__.py", line 1, in <module>
    from exo.api.chatgpt_api import ChatGPTAPI
  File "/Users/tfr/Documents/TestArea/exo/exo/api/chatgpt_api.py", line 6, in <module>
    from aiohttp import web
ModuleNotFoundError: No module named 'aiohttp'
```

Here is some info that might.be useful:
```
% uname -a
Darwin studio.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000 arm64

% python --version
Python 3.10.14
```

**Comment by troelsfr** [comment]
How to fix:
```
pip install aiohttp
```

**Comment by AlexCheema** [comment]
Good catch. This was introduced in https://github.com/exo-explore/exo/commit/f2895cbceefea1249b62ae32ca5664df4e2d4511. Added aiohttp to the `requirements.txt` now.
