### ISSUE TITLE
Message.init() got an unexpected keyword argument 'name' + FIX

### ISSUE THREAD

**Issue by stephanj** [exo-explore/exo#81]
When using the ChatGPT API the following exception is sometimes thrown:

```
TypeError: Message.init() got an unexpected keyword argument 'name'
Error handling request
Traceback (most recent call last):
  File "/aiohttp/web_protocol.py", line 452, in handlerequest
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "exo/exo/api/chatgpt_api.py", line 166, in handle_post_chat_completions
    messages = [Message(msg) for msg in data['messages']]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "exo/exo/api/chatgpt_api.py", line 166, in <listcomp>
    messages = [Message(msg) for msg in data['messages']]
                ^^^^^^^^^^^^^^
TypeError: Message.init() got an unexpected keyword argument 'name'
```

File: exo/api/chatgpt_api.py

It seems there's an issue with how the Message class is being initialized.
Here's a revised version of the relevant part:

```python

class Message:
    def __init__(self, role: str, content: str):
        self.role = role
        self.content = content

# In the handle_post_chat_completions function:
messages = []
for msg in data['messages']:
    if 'role' in msg and 'content' in msg:
        messages.append(Message(role=msg['role'], content=msg['content']))
    else:
        return web.json_response({'error': 'Invalid message format'}, status=400)
```

**Comment by AlexCheema** [comment]
Thanks for creating the issue. Fixed.
